name: technician_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.17
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  flutter_cache: ^0.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.5
  flutter_svg: ^1.0.3
  provider: ^6.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
