name: technician_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.17
  file_picker: ^4.6.1
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.2
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  flutter_cache: ^0.1.0
  flutter_local_notifications: ^9.5.3+1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.5
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  open_file: ^3.2.1
  page_transition: ^2.0.5
  path_provider: ^2.0.11
  pdf: ^3.8.1
  provider: ^6.0.3
  table_calendar: ^3.0.6
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
